# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ae2b93832d39fef806c732355643a1ed4603d2e404421f07c20c303f64ecb89888840befab8a1c108912523d18daefcdfb306ad71398d7233d2d3a9f069d2ea6

test:
  secret_key_base: e2a115dd01ec0cdf26486aa12e2a194ff5378a84db127cc2fffce5cab1bf8bfdc06cc250fe522c36fcd7b30c94d93685c5c9db6a1401ba524bde3bc5af41bda2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
